/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        tertiary: "#5f5e5b",
        "primary-fixed": "#ffdbcc",
        "tertiary-fixed": "#e5e2dd",
        "surface-container-highest": "#e9e1dc",
        "on-secondary-fixed-variant": "#4c463c",
        surface: "#fff8f5",
        secondary: "#645d53",
        "surface-container-low": "#fbf2ed",
        "secondary-fixed-dim": "#cfc5b9",
        "on-primary": "#ffffff",
        "tertiary-container": "#969591",
        "on-secondary-fixed": "#1f1b13",
        "on-primary-fixed": "#351000",
        "on-surface": "#1e1b18",
        "primary-fixed-dim": "#feb694",
        "surface-bright": "#fff8f5",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e9e1dc",
        "surface-container-lowest": "#ffffff",
        primary: "#875135",
        "inverse-surface": "#34302c",
        "on-secondary-container": "#686257",
        "secondary-container": "#e8ded1",
        "surface-container-high": "#efe6e2",
        "on-tertiary-container": "#2e2e2b",
        "on-secondary": "#ffffff",
        "inverse-primary": "#feb694",
        "primary-container": "#c68667",
        "on-background": "#1e1b18",
        "on-surface-variant": "#52443d",
        "on-tertiary-fixed": "#1c1c19",
        "outline-variant": "#d7c2ba",
        "secondary-fixed": "#ebe1d4",
        "on-error-container": "#93000a",
        outline: "#85746c",
        "surface-dim": "#e1d8d4",
        "surface-container": "#f5ece7",
        "surface-tint": "#875135",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#6b3a20",
        "tertiary-fixed-dim": "#c8c6c2",
        "on-tertiary-fixed-variant": "#474743",
        background: "#fff8f5",
        "on-primary-container": "#4c220a",
        "inverse-on-surface": "#f8efea",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      spacing: {
        xl: "80px",
        sm: "12px",
        lg: "48px",
        xs: "4px",
        "margin-mobile": "16px",
        gutter: "24px",
        base: "8px",
        "container-max": "1280px",
        md: "24px",
      },
      fontFamily: {
        serif: ["'DM Serif Display'", "serif"],
        sans: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
}
